# Generated by Django 2.2.2 on 2019-06-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabiri_gis', '0002_auto_20190625_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constituency',
            options={'managed': False, 'verbose_name_plural': 'Constituencies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False, 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'managed': False, 'verbose_name_plural': 'Counties'},
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='dhis2parentid',
            field=models.ForeignKey(db_column='dhis2parentid', default=37615001008, on_delete=django.db.models.deletion.DO_NOTHING, to='tabiri_gis.Ward', to_field='ward_dhis2_id'),
        ),
        migrations.AddField(
            model_name='vaccinedemandfeature',
            name='orgunitid',
            field=models.ForeignKey(db_column='orgunitid', default=37615001008, on_delete=django.db.models.deletion.CASCADE, to='tabiri_gis.HealthFacility'),
        ),
        migrations.AddField(
            model_name='ward',
            name='const_code',
            field=models.ForeignKey(db_column='constituency_code', default=37615001008, on_delete=django.db.models.deletion.CASCADE, to='tabiri_gis.Constituency', to_field='const_code'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_dhis2_id',
            field=models.BigIntegerField(db_column='ward_dhis2_id', default=37615001008, unique=True),
        ),
    ]
