# Generated by Django 2.2.2 on 2019-06-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabiri_gis', '0003_auto_20190625_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinedemandfeature',
            name='bcg_vaccine_demand',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vaccinedemandfeature',
            name='dpt_vaccine_demand',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vaccinedemandfeature',
            name='measles_vaccine_demand',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vaccinedemandfeature',
            name='opv_vaccine_demand',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vaccinedemandfeature',
            name='pneumococal_vaccine_demand',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vaccinedemandfeature',
            name='tetanus_toxoid_vaccine_demand',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vaccinedemandfeature',
            name='vit_a_vaccine_demand',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vaccinedemandfeature',
            name='yellow_fever_vaccine_demand',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
