# Generated by Django 2.2.2 on 2019-06-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabiri_gis', '0006_wardvaccinedemand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyVaccineDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('totalbirths', models.BigIntegerField(blank=True, default=0, null=True)),
                ('totalchildrenvaccinated', models.BigIntegerField(blank=True, default=0, null=True)),
                ('bcg_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('tetanus_toxoid_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('measles_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('opv_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('pneumococal_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('vit_a_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('yellow_fever_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('dpt_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('ref_id', models.ForeignKey(db_column='county_cod', on_delete=django.db.models.deletion.CASCADE, to='tabiri_gis.County')),
            ],
            options={
                'ordering': ['month', 'year'],
            },
        ),
        migrations.CreateModel(
            name='ConstituencyVaccineDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('totalbirths', models.BigIntegerField(blank=True, default=0, null=True)),
                ('totalchildrenvaccinated', models.BigIntegerField(blank=True, default=0, null=True)),
                ('bcg_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('tetanus_toxoid_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('measles_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('opv_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('pneumococal_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('vit_a_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('yellow_fever_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('dpt_vaccine_demand', models.BigIntegerField(blank=True, default=0, null=True)),
                ('ref_id', models.ForeignKey(db_column='const_code', on_delete=django.db.models.deletion.CASCADE, to='tabiri_gis.Constituency')),
            ],
            options={
                'ordering': ['month', 'year'],
            },
        ),
    ]
