# Generated by Django 2.2.2 on 2019-06-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabiri_gis', '0007_constituencyvaccinedemand_countyvaccinedemand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='orgunitid',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
