# Generated by Django 2.2.2 on 2019-06-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabiri_gis', '0009_auto_20190625_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineforecastlogs',
            name='orgunitid',
        ),
        migrations.AddField(
            model_name='vaccineforecastlogs',
            name='ref_id',
            field=models.ForeignKey(db_column='ref_id', default=37615001008, on_delete=django.db.models.deletion.CASCADE, to='tabiri_gis.HealthFacility', to_field='dhis2id'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='dhis2id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='orgunitid',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
